import React from 'react';

const PolicyLayout = ({ title, lastUpdated, children }) => (
    <div className="animate-fadeIn" style={{ paddingTop: '160px', paddingBottom: '100px' }}>
        <div className="container" style={{ maxWidth: '900px' }}>
            <h1 className="title-gradient" style={{ fontSize: '3rem', marginBottom: '1rem' }}>{title}</h1>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '3rem' }}>Last Updated: {lastUpdated}</p>
            <div className="glass legal-content" style={{ padding: '3rem', borderRadius: '2rem', lineHeight: '1.8', color: 'var(--text-secondary)' }}>
                {children}
            </div>
            <div style={{ marginTop: '2rem', textAlign: 'center' }}>
                <p style={{ color: 'var(--text-muted)' }}>Questions? Contact our legal team at <a href="mailto:support@picpro.ai" style={{ color: 'var(--primary)', textDecoration: 'none' }}>support@picpro.ai</a></p>
            </div>
        </div>
        <style>{`
            .legal-content h2 { color: var(--text-primary); margin: 2rem 0 1rem; font-size: 1.5rem; }
            .legal-content h3 { color: var(--text-primary); margin: 1.5rem 0 1rem; font-size: 1.25rem; }
            .legal-content p { margin-bottom: 1.5rem; }
            .legal-content ul { margin-bottom: 1.5rem; padding-left: 1.5rem; }
            .legal-content li { margin-bottom: 0.5rem; }
            .legal-content strong { color: var(--text-primary); }
        `}</style>
    </div>
);

const PrivacyPolicy = () => {
    return (
        <PolicyLayout title="Privacy Policy" lastUpdated="February 1, 2026">
            <h2>1. Information We Collect</h2>
            <p>At PicPro AI, we collect information to provide a better experience. This includes:</p>
            <ul>
                <li><strong>Account Information:</strong> Google profile data (email, name, picture) provided via OAuth.</li>
                <li><strong>Service Content:</strong> Images you upload and content generated by our AI tools.</li>
                <li><strong>Usage Data:</strong> Information on how you interact with our tools and dashboard.</li>
            </ul>

            <h2>2. How We Use Information</h2>
            <p>We use your data strictly to provide the PicPro AI services. We <strong>never sell or share your personal data or content with third parties</strong> for marketing or advertising purposes.</p>

            <h2>3. Data Retention & Deletion</h2>
            <p>We respect your storage limits and privacy:</p>
            <ul>
                <li><strong>30-Day Storage:</strong> Uploaded images and generated content are stored on our servers for 30 days.</li>
                <li><strong>Automatic Deletion:</strong> Content is automatically and permanently deleted after 30 days of inactivity.</li>
                <li><strong>Manual Deletion:</strong> You can delete your creations at any time through your dashboard.</li>
            </ul>

            <h2>4. Data Security</h2>
            <p>We implement industry-standard security measures to protect your data. All communication is encrypted via SSL/TLS, and content is stored in secure Firebase environments.</p>

            <h2>5. Service Providers</h2>
            <p>We use trusted third-party providers (Google Cloud, Firebase, ComfyDeploy) to host our service and process AI requests. These providers are bound by strict data protection agreements.</p>

            <h2>6. Governing Law</h2>
            <p>This policy is governed by the laws of the <strong>State of Delaware, United States</strong>.</p>
        </PolicyLayout>
    );
};

export default PrivacyPolicy;
